import { Inter } from "next/font/google";
import "./_styles/globals.css";
import dynamic from 'next/dynamic';
import Footer from "./_components/Footer/Footer";
import { ReactNode } from "react";

const Header = dynamic(() => import('./_components/Header/Header'), { ssr: true });

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="w-full bg-white relative">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
